[package]
name = "shitsploit"
version = "0.1.0"
edition = "2021"

[dependencies]
memory_utils = "0.2.0"
device_query = "0.2"
once_cell = "1.19"
mlua = { version = "0.10.3", features = ["luau", "vendored", "send"] }
