#[allow(non_snake_case)]
#[allow(dead_code)]
pub struct Offsets {
    pub Sit                   : usize,
    pub Team                  : usize,
    pub Name                  : usize,
    pub Parent                : usize,
    pub Health                : usize,
    pub Camera                : usize,
    pub PlaceId               : usize,
    pub UserId                : usize,
    pub FogColor              : usize,
    pub Velocity              : usize,
    pub Position              : usize,
    pub HipHeight             : usize,
    pub CameraPos             : usize,
    pub JumpPower             : usize,
    pub Children              : usize,
    pub WalkSpeed             : usize,
    pub LocalPlayer           : usize,
    pub PartSize              : usize,
    pub Primitive             : usize,
    pub CameraSubject         : usize,
    pub MousePosition         : usize,
    pub MoveDirection         : usize,
    pub CanCollide            : usize,
    pub ClassDescriptor       : usize,
    pub ChildrenEnd           : usize,
    pub OnDemandInstance      : usize,
    pub WalkSpeedCheck        : usize,
    pub ModelInstance         : usize,
    pub MeshPartColor3        : usize,
    pub FakeDataModelPointer  : usize,
    pub FakeDataModelToData   : usize,
}
